//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.04 at 12:18:49 AM ALMT 
//


package kz.e16training.xmltask.entity.classTypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PairType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PairType">
 *   &lt;complexContent>
 *     &lt;extension base="{}SoloType">
 *       &lt;sequence>
 *         &lt;element name="Dancer" type="{}Dancer"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PairType", propOrder = {
    "rest"
})
@XmlSeeAlso({
    MassType.class
})
public class PairType
    extends SoloType
{

    @XmlElementRef(name = "Dancer", type = JAXBElement.class, required = false)
    protected List<JAXBElement<Dancer>> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Dancer" is used by two different parts of a schema. See: 
     * line 82 of file:/C:/IdeaWrk/EpamCourse/XMLtask/src/main/resources/xmldance.xsd
     * line 74 of file:/C:/IdeaWrk/EpamCourse/XMLtask/src/main/resources/xmldance.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Dancer }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Dancer>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<Dancer>>();
        }
        return this.rest;
    }

}
