//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.04 at 12:18:49 AM ALMT 
//


package kz.e16training.xmltask.entity.classTypes;

import kz.e16training.xmltask.entity.enumTypes.TypeOfDance;
import kz.e16training.xmltask.entity.enumTypes.TypeOfMusic;
import kz.e16training.xmltask.entity.enumTypes.TypeOfScene;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for UnitOfDance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnitOfDance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DanceType" type="{}TypeOfDance"/>
 *         &lt;element name="SceneType" type="{}TypeOfScene"/>
 *         &lt;element name="MusicType" type="{}TypeOfMusic"/>
 *         &lt;element name="DanceGroup" type="{}DanceGroup" minOccurs="0"/>
 *         &lt;element name="DancersType" type="{}NumberOfDancers"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DanceID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnitOfDance", propOrder = {
    "danceType",
    "sceneType",
    "musicType",
    "danceGroup",
    "dancersType"
})
public class UnitOfDance {

    @XmlElement(name = "DanceType", required = true)
    @XmlSchemaType(name = "string")
    protected TypeOfDance danceType;
    @XmlElement(name = "SceneType", required = true)
    @XmlSchemaType(name = "string")
    protected TypeOfScene sceneType;
    @XmlElement(name = "MusicType", required = true)
    @XmlSchemaType(name = "string")
    protected TypeOfMusic musicType;
    @XmlElement(name = "DanceGroup")
    protected DanceGroup danceGroup;
    @XmlElement(name = "DancersType", required = true)
    protected NumberOfDancers dancersType;
    @XmlAttribute(name = "DanceID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String danceID;

    /**
     * Gets the value of the danceType property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfDance }
     *     
     */
    public TypeOfDance getDanceType() {
        return danceType;
    }

    /**
     * Sets the value of the danceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfDance }
     *     
     */
    public void setDanceType(TypeOfDance value) {
        this.danceType = value;
    }

    /**
     * Gets the value of the sceneType property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfScene }
     *     
     */
    public TypeOfScene getSceneType() {
        return sceneType;
    }

    /**
     * Sets the value of the sceneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfScene }
     *     
     */
    public void setSceneType(TypeOfScene value) {
        this.sceneType = value;
    }

    /**
     * Gets the value of the musicType property.
     * 
     * @return
     *     possible object is
     *     {@link TypeOfMusic }
     *     
     */
    public TypeOfMusic getMusicType() {
        return musicType;
    }

    /**
     * Sets the value of the musicType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeOfMusic }
     *     
     */
    public void setMusicType(TypeOfMusic value) {
        this.musicType = value;
    }

    /**
     * Gets the value of the danceGroup property.
     * 
     * @return
     *     possible object is
     *     {@link DanceGroup }
     *     
     */
    public DanceGroup getDanceGroup() {
        return danceGroup;
    }

    /**
     * Sets the value of the danceGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link DanceGroup }
     *     
     */
    public void setDanceGroup(DanceGroup value) {
        this.danceGroup = value;
    }

    /**
     * Gets the value of the dancersType property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfDancers }
     *     
     */
    public NumberOfDancers getDancersType() {
        return dancersType;
    }

    /**
     * Sets the value of the dancersType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfDancers }
     *     
     */
    public void setDancersType(NumberOfDancers value) {
        this.dancersType = value;
    }

    /**
     * Gets the value of the danceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDanceID() {
        return danceID;
    }

    /**
     * Sets the value of the danceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDanceID(String value) {
        this.danceID = value;
    }

}
